# Wait until three days after release to install new versions of packages
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@arphi/*"
# We don’t need to run these build scripts, so explicitly disallow them as a minor security measure.
allowBuilds:
  esbuild: false
  unrs-resolver: false
