# Wait until three days after release to install new versions of packages
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@arphi/*"
  # This is too recent, but this should fix my issue. To remove later.
  - "@astrojs/compiler-*"
  # Renovate security update: nodemailer@8.0.4 || 8.0.5
  - nodemailer@8.0.4 || 8.0.5
  # Renovate security update: astro@6.1.6
  - astro@6.1.6
  # Renovate security update: @astrojs/node@10.0.5
  - "@astrojs/node@10.0.5"
onlyBuiltDependencies:
  - cypress
  - esbuild
  - sharp
  - unrs-resolver
