# Wait until three days after release to install new versions of packages
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@arphi/*"
  # Renovate security update: @astrojs/node@9.5.4
  - "@astrojs/node@9.5.4"
onlyBuiltDependencies:
  - cypress
  - esbuild
  - sharp
  - unrs-resolver
