export const SMTP_CATCHER_HOST = "127.0.0.1";
export const SMTP_CATCHER_SMTP_PORT = 2525;
export const SMTP_CATCHER_CONTROL_PORT = 2526;
export const SMTP_CATCHER_CONTROL_URL = `http://${SMTP_CATCHER_HOST}:${SMTP_CATCHER_CONTROL_PORT}`;
