name: Release
permissions: {}

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash

env:
  CI: true
  FORCE_COLOR: true

jobs:
  release:
    name: Release
    if: ${{ github.repository_owner == 'ArmandPhilippot' }}
    permissions:
      contents: write # to create release (changesets/action)
      issues: write # to post issue comments (changesets/action)
      pull-requests: write # to create pull request (changesets/action)
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24.14.1
          package-manager-cache: false

      - name: Install dependencies
        run: pnpm i

      - name: Create Release Pull Request
        uses: changesets/action@6a0a831ff30acef54f2c6aa1cbbc1096b066edaf # v1.7.0
        with:
          version: pnpm ci:version
          commit: "chore: new release"
          title: "chore: new release candidate"
          publish: pnpm ci:release
        env:
          # Needs access to push to main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
